### ISSUE TITLE
Tyracraft

### ISSUE THREAD

**Issue by PetrusRots** [Wellinator/tyracraft#24]
Vaya, por favor agregue pantalla dividida multijugador en la próxima actualización, ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡ WOOW, increíble, buen trabajo, gente, sigan así (: esperando este increíble sitio en el que crean juegos que no eran posibles, hicieron algo que Sony no pudo (: SÍAAAA (: WOWWWWWWW, POR FAVOR, HAGAN LA PANTALLA DIVIDIDA MULTIJUGADOR, POR FAVOR, TODOS ESTAMOS FELICES DE VER ESTO EN PS2).
===============================================================================
Wow, please add split screen multiplayer in the next update,!!!!!!!! WOOW amazing good job people keep up the good work (: waiting for this amazing tyracraft you make games that weren't possible, you did something that Sony couldn't (: YEAAAAA (: WOWWWWWWW PLEASE MAKE THE SCREEN DIVIDED splitscreen MULTIPLAYER PLEASE WE ARE ALL HAPPY TO SEE THIS ON PS2).

**Comment by Wolf3s** [comment]
Hola mi amigo, Acalma te.

**Comment by Wellinator** [comment]
Please use the Discord for this stuff! Thx.
