### ISSUE TITLE
getting a error screen when running from pcsx2 on windows 10

### ISSUE THREAD

**Issue by ChoopsMan** [Wellinator/tyracraft#27]
When i drag and drop the .elf file on PCSX2 it shows the tyra logo and then crashes to this screen: 
![help](https://github.com/user-attachments/assets/77cbf296-8d09-4548-944d-e13327fb7953)

**Comment by ChoopsMan** [comment]
and yes i did extract the assets correctly. the assets are in a folder i named tyracraft.

**Comment by Wolf3s** [comment]
> and yes i did extract the assets correctly. the assets are in a folder i named tyracraft.

drag the elf file inside of the tyracraft folder on the root.

**Comment by ChoopsMan** [comment]
thats what i did, still happens

**Comment by Wolf3s** [comment]
You should enable hostfs.

**Comment by ChoopsMan** [comment]
quick question: how do i do that?

**Comment by Wolf3s** [comment]
PCSX2->Configurations->Emulation->Enable Host Filesystem.

**Comment by ChoopsMan** [comment]
thanks! it works now.

**Comment by mrfiguy** [comment]
dude WHY AM I GETTING EMAILS 24/7 FROM THIS POST
