### ISSUE TITLE
Uma coisa simples para adicionar

### ISSUE THREAD

**Issue by Dydanbr** [Wellinator/tyracraft#8]
Uma coisa simples mais que muda muito, quando uma pessoa tiver jogando o tyracraft, antes de eu explicar vou falar uma coisa pra vocês desenvolvedores entenderem, bem na ultima atualização que foi de setembro, vocês adicionaram uma opção pra personalizar o mundo, se quer com água sem água, se quer plano, se quer árvores, em fim, aí uma pessoa tá jogando no terreno precedural e quer ir para o plano um pouco, aí ela vai ter que desligar o ps2 e ligar de novo entrar no jogo pra conseguir fazer outro mundo, isso é muito ruim, então tipo, faz um script de quando clicar no start ir pra uma nova cena(menu) com duas opções voltar pra gameplay onde voc
ê estava jogando e a segunda opção sair do mundo e voltar para o menu principal, isso é uma coisa pequena mas faz diferença, eu não sei muito de programação sei poucas coisas de criação de jogo, mais espero que vocês reflitam essa pequena causa, eu so to tentando ajudar.

**Comment by Wellinator** [comment]
Yeah this feature will be added in the next feature, it's the "in game menu".
Thx for notice! Pls write comments in english, so everyone can read or translate...
