### ISSUE TITLE
Contribuição

### ISSUE THREAD

**Issue by Dydanbr** [Wellinator/tyracraft#9]
Quero ajudar vocês com scripts texturas e mais seria possivel?

**Comment by wolfysdl** [comment]
> Quero ajudar vocês com scripts texturas e mais seria possivel?

Sim

**Comment by Wellinator** [comment]
Closed by inactivity

**Comment by PetrusRots** [comment]
its fine i barely touched but i did it to support you i have some post
question at issue section on your page btw THANKS FOR EVERYTHING you have
done so far
